smol-rs/async-lock

async-barrier/Cargo.toml, async-barrier/src/lib.rs, async-mutex/Cargo.toml, async-mutex/src/lib.rs, async-rwlock/Cargo.toml, async-rwlock/src/lib.rs, async-semaphore/src/lib.rs
Since the `event-listener` constructor is a const fn, all constructors of this repository can be too :)
=> Opti: make new() a const fn

src/mutex.rs, src/rwlock.rs
`compare_and_swap` is deprecated in 1.50. (https://github.com/rust-lang/rust/pull/79261)
This patch replaces the uses of `compare_and_swap` with `compare_exchange`.
See also the document about `compare_and_swap` -> `compare_exchange(_weak)` migration: https://doc.rust-lang.org/nightly/core/sync/atomic/struct.AtomicUsize.html#migrating-to-compare_exchange-and-compare_exchange_weak
=> Replace deprecated compare_and_swap with compare_exchange

.github/workflows/build-and-test.yaml, Cargo.toml, src/mutex.rs, tests/barrier.rs, tests/mutex.rs, tests/rwlock.rs
Still, testing, but would you be open to supporting WASM? It looks like all that is needed is an extra dep for supporting `std::time::Instant` on web.
It's behind a feature flag so it doesn't effect anybody unconcerned with WASM.
=> 🌐 Add WASM Support

src/mutex.rs, tests/mutex.rs
The future returned by lock_arc would already resolve to a
MutexGuardArc that kept the Arc<Mutex> alive. Unfortunately, sometimes
one needs to store the future itself, not the MutexGuardArc and the
future had a reference to the Arc<Mutex>.
With this patch, the future itself also has a Arc<Mutex>.
=> Simplify using lock_arc

src/mutex.rs, tests/mutex.rs, tests/rwlock.rs
- Remove needs of `#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]` per `#[test]`
- Use `cfg(target_family = "wasm")` that indicates both wasm32&wasm64. Currently, we can use this only in tests because `cfg(target_family = "wasm")` requires Rust 1.54.
=> Simplify wasm tests

CHANGELOG.md, Cargo.toml
Changes:
- Add `OnceCell`. (#27)
- Support wasm64 (https://github.com/smol-rs/async-lock/commit/ab4362fe811a294641595ee84e46dd5e3af0986e).
=> Release 2.6.0

src/barrier.rs, src/lib.rs, src/mutex.rs, src/rwlock.rs, src/semaphore.rs
The goal of this PR is to resolve #4 by adding manually-implemented futures to `Mutex`, `RwLock`, `Barrier` and `Semaphore`, similar to smol-rs/async-channel#33. This aim of this PR is to improve semantics for when `poll` is the only means available to poll a future. The main downside is that is replaces the elegant `async` blocks with some more garish manual futures, but I tried to keep the semantics and ordering of logic the same throughout.
I avoided adding implementations for `OnceCell`, since with the closures and self-referential ideas it's not possible to implement without either a significant amount of hard-to-check `unsafe` code or overextensive heap allocation.
Closes #4
Closes #5
=> Replace some async blocks with manual futures

src/mutex.rs, src/rwlock.rs, src/semaphore.rs
`#[clippy::has_significant_drop]` tells that a structure should be considered when evaluating some lints. Examples of such behavior are the existent `clippy::significant_drop_in_scrutinee` and the soon-to-be-finished https://github.com/rust-lang/rust-clippy/issues/9399.
=> Mark `MutexGuard` with `#[clippy::has_significant_drop]`

CHANGELOG.md, Cargo.toml
- Replace some `async` blocks with manual futures (#34)
- Remove our dependency on `futures-lite` (#36)
- Mark guard types with `#[clippy::has_significant_drop]` (#37)
=> Release version 2.7.0

Cargo.toml, src/mutex.rs, src/rwlock.rs, src/semaphore.rs, tests/common/mod.rs, tests/mutex.rs, tests/rwlock.rs, tests/semaphore.rs
Fixes #41
I also added a test for this for each of `Mutex`/`RwLock`/`Semaphore`. The existing tests almost all use different threads when tasks contend for locks so they wouldn't catch this.
=> don't busy wait in SemaphoreGuard::acquire_arc

src/semaphore.rs, tests/semaphore.rs
Allows increasing the permit count of the semaphore after creation.
=> Add `Semaphore::add_permits()`

src/mutex.rs, src/rwlock.rs, src/rwlock/raw.rs, tests/rwlock.rs
And refactor `RwLock` implementation into non-generic core and generic interface, which should reduce binary sizes.
Fixes #9
=> Make `RwLockReadGuard` covariant

src/lib.rs, src/rwlock.rs, src/rwlock/futures.rs, src/rwlock/raw.rs, tests/rwlock.rs
=> Add reference-counted versions of `RwLock` guards

src/mutex.rs, src/rwlock/futures.rs
This ensures that `Send`/`Sync` bounds for each future match those of the value produed by the future.
=> Loosen `Send`/`Sync` bounds on futures

src/mutex.rs
`MutexGuardArc` implements `Sync` regardless of whether `T` is `Send`, but `source()` allows dropping `T` from a different thead than it was created in.
This is a breaking change, but a necessary soundness fix.
The alternative would be to change the `Sync` impl for  `MutexGuardArc` to require `T: Send + Sync`.
=> Fix UB in `MutexGuardArc::source`

.github/workflows/ci.yml, Cargo.toml, src/barrier.rs, src/lib.rs, src/mutex.rs, src/once_cell.rs, src/rwlock.rs, src/rwlock/futures.rs, src/rwlock/raw.rs, src/semaphore.rs, tests/common/mod.rs
Testing to make sure that `event-listener v3.0.0` actually works before we release smol-rs/event-listener#58
Needs smol-rs/event-listener#60
=> Bump to event-listener v3.0.0

Cargo.toml, src/barrier.rs, src/mutex.rs, src/rwlock.rs, src/rwlock/futures.rs, src/rwlock/raw.rs, src/semaphore.rs, tests/barrier.rs, tests/mutex.rs, tests/rwlock.rs, tests/semaphore.rs
Supersedes #25 and #39, needs smol-rs/event-listener-strategy#6
=> Support blocking and non-blocking operations on the same mutex

src/lib.rs
=> Add a note comparing against std types

src/mutex.rs, src/rwlock.rs, src/semaphore.rs, tests/mutex.rs, tests/rwlock.rs, tests/semaphore.rs
Adds:
- `Rwlock::read_arc_blocking`
- `RwLock::upgradable_read_arc_blocking`
- `RwLock::write_arc_blocking`
- `RwLockUpgradableReadGuardArc::upgrade_blocking`
- `Semaphore::acquire_arc_blocking`
=> Add missing `Arc` blocking methods

.github/workflows/ci.yml, Cargo.toml, src/barrier.rs, src/lib.rs, src/mutex.rs, src/once_cell.rs, src/rwlock/futures.rs, src/rwlock/raw.rs, src/semaphore.rs, tests/barrier.rs, tests/rwlock.rs
=> Port to event-listener v5.0.0

tests/rwlock.rs
```
error: the item `Future` is imported redundantly
--> tests/rwlock.rs:11:5
|
9  | use futures_lite::prelude::*;
|     ------------------------ the item `Future` is already imported here
10 | #[cfg(not(target_family = "wasm"))]
11 | use std::future::Future;
|     ^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
```
=> Remove redundant import

Cargo.toml, src/barrier.rs, tests/barrier.rs, tests/mutex.rs, tests/rwlock.rs
This commit replaces async-channel in some tests with flume. It appears
that async-channel doesn't work under MIRI but flume does, so we can
work around this for now by replacing it with flume.
cc https://github.com/smol-rs/async-channel/issues/85
=> Replace async-channel with flume

.github/workflows/ci.yml, Cargo.toml, src/barrier.rs, src/lib.rs, src/mutex.rs, src/once_cell.rs, src/rwlock.rs, src/rwlock/raw.rs, src/semaphore.rs, tests/loom.rs
Adds loom instrumentation to help find bugs
=> Instrument with loom

Cargo.toml
I added half of a portable-atomic implementation in #86 and forgot to finish it. This removes it prior to release.
=> Remove unused portable-atomic feature

src/barrier.rs, src/mutex.rs, src/once_cell.rs, src/rwlock.rs, src/rwlock/raw.rs
Two lints silenced for https://github.com/smol-rs/async-lock/issues/90
Closes #90
=> chore: Fix lints

.github/workflows/ci.yml, src/once_cell.rs, src/rwlock.rs, src/rwlock/futures.rs, src/rwlock/raw.rs
See https://github.com/smol-rs/.github/pull/1 for details about reusable workflows.
=> ci: Use reusable workflows for fmt and security_audit
